### PR TITLE
Committing test2 TO  branchX

### PR DESCRIPTION
**Pull request by EnayathFazleAhmed**
hii i have commited test 2 so please review and approve my code
Regards from Enayath

### CODE REVIEW

**Comment by EnayathFazleAhmed** [comment]
Your code is okay ... just add another statement to your code

**Comment by MoeFazle** [comment]
your code is okay just add another statement to the code and repush

**Comment by EnayathFazleAhmed** [comment]
i have done the code .. please approve

**Comment by MoeFazle** [comment]
perfect ! 
go ahead and merge to the master branch

**Pull request merged**
